# Fixed _config.yml
title: LEGOLAND Media Analytics
github_repo: "healthmedia" 
baseurl: "/healthmedia"
description: "Social Media Analytics for LEGOLAND California"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  - jekyll-remote-theme
layouts_dir: _layouts

# Header navigation pages
header_pages:
- navigation/aboutus.md
- navigation/mainhome.md
- navigation/teamteach/mainhome.md
- navigation/blog.md
- navigation/search.md

# Site author
author:
  name: LEGOLAND Analytics Team
  email: team@legolandanalytics.com


# SEO settings
lang: en
timezone: America/Los_Angeles

Server: https://healthmedia.nighthawkcodingsociety.com/
Domain: nighthawkcodingsociety.com
Subdomain: healthmedia






