title: Legoland Media
github_repo: "healthmedia" 
baseurl: "/healthmedia"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
- navigation/aboutus.md
- navigation/teamteach/mainhome.md
- navigation/healthmedia/mainhome.md
- navigation/blog.md
- navigation/search.md

